=== BrainTech/jsignalml/SignalML_2_0.dtd
<!ELEMENT signalml (header, (file | assert)*)>

<!ELEMENT header (format | text_info | url)*>
<!--<!ELEMENT format (#PCDATA)>-->
<!ELEMENT text_info (#PCDATA)>
<!ELEMENT url (#PCDATA)>

<!ELEMENT file (param | assert | data)*>
<!ELEMENT param (arg*,
          (expr
          | (offset, format) | (format, offset)
          | (pattern, line?) | (line, pattern)
	  | xpath)
)>
<!ELEMENT assert (expr)>
<!ELEMENT arg EMPTY>
<!ELEMENT data EMPTY>

<!ENTITY % file_types "binary|text|xml">

<!ELEMENT expr (#PCDATA)>
<!ELEMENT offset (#PCDATA)>
<!ELEMENT format (#PCDATA)>
<!ELEMENT pattern (#PCDATA)>
<!ELEMENT line (#PCDATA)>
<!ELEMENT xpath (#PCDATA)>

<!ATTLIST file
	  type   (%file_types;) #REQUIRED
          name   CDATA #IMPLIED
>
<!ATTLIST param
	  id     ID    #REQUIRED
	  type   CDATA #IMPLIED
	  units  CDATA #IMPLIED
>
<!ATTLIST assert
	  id     ID    #REQUIRED
>
<!ATTLIST arg
	  type   CDATA #REQUIRED
	  name   CDATA #REQUIRED
>
<!ATTLIST data
	  mapping IDREF #IMPLIED
	  format  IDREF #IMPLIED
>

=== BrainTech/jsignalml/specs/MCS.xml
<?xml version="1.0"?>
<!DOCTYPE signalml SYSTEM "SignalML_2_0.dtd">
<signalml>

<header>
 <text_info>MCS data format</text_info>
 <url>http://www.multichannelsystems.com</url>
</header>

<file type='binary'>
  <param id='magic_MCSSTRM' type='str'>
    <format>'|S8'</format>
    <offset>0</offset>
  </param>
  <assert id='magic_MCSSTRM_check'>
    <expr>magic_MCSSTRM == "MCSSTRM "</expr>
  </assert>

  <!-- this is not used, it's a const -->
  <param id='length_of_file' type='int'>
    <format>'&lt;i8'</format>
    <offset>8</offset>
  </param>

  <assert id='length_of_file_check'>
    <expr>length_of_file == -1</expr>
  </assert>

  <param id='magic_LISThdr' type='str'>
    <format>'|S8'</format>
    <offset>16</offset>
  </param>
  <assert id='magic_LISThdr_check'>
    <expr>magic_LISThdr == "LISThdr "</expr>
  </assert>

  <param id='size_of_LISThdr' type='int'>
    <format>'&lt;i8'</format>
    <offset>24</offset>
  </param>

  <param id='magic_MCSHDR' type='str'>
    <format>'|S8'</format>
    <offset>32</offset>
  </param>
  <assert id='magic_MCSHDR_check'>
    <expr>magic_MCSHDR == "MCSHDR  "</expr>
  </assert>
  
  <param id='size_of_MCSHDR' type='int'>
    <format>'&lt;i8'</format>
    <offset>40</offset>
  </param>

  <param id='header_version' type='int'>
    <format>'&lt;i2'</format>
    <offset>48</offset>
  </param>
  <assert id='header_version_check'>
    <expr>header_version &lt;= 10</expr>
  </assert>
  
 
</file>

</signalml>

=== BrainTech/jsignalml/specs/BytesTest.xml
<?xml version="1.0"?>
<!DOCTYPE signalml SYSTEM "SignalML_2_0.dtd">
<signalml>

	<header>
		<format_id>
		  <info>SignalML definition for dummy format, designed to test bytes type</info>
		</format_id>
	</header>

	<param id='bytes1test' type='bytes'>
		<expr>B'abcdABCD'</expr>
	</param>

	<param id='bytes2test' type='bytes'>
		<expr>b'123456789'</expr>
	</param>

	<param id='bytes3test' type='bytes'>
		<expr>b"ABCDabcd"</expr>
	</param>

	<param id='bytes4test' type='bytes'>
		<expr>B"0abcd"</expr>
	</param>

</signalml>

=== BrainTech/jsignalml/specs/BoolTest.xml
<?xml version="1.0"?>
<!DOCTYPE signalml SYSTEM "SignalML_2_0.dtd">
<signalml>

	<header>
		<format_id>
		  <description>SignalML definition for dummy codec, designed to test bool type</description>
		</format_id>
	</header>

	<param id='paramint1' type='int'>
		<expr>1</expr>
	</param>

	<param id='paramint2' type='int'>
		<expr>2</expr>
	</param>

	<param id='paramstr1' type='str'>
		<expr>"true"</expr>
	</param>

	<param id='boolp1' type='bool'>
		<expr>true</expr>
	</param>

	<param id='boolp2' type='bool'>
		<expr>false</expr>
	</param>

	<param id='boolp3' type='bool'>
		<expr>TRUE</expr>
	</param>

	<if id='if1' test='paramint1 == paramint2'>
		<param id='p1' type='bool'>
			<expr>paramint1 == paramint2</expr>
		</param>
	<else>
		<param id='p1' type='bool'>
			<expr>paramint2 != paramint1</expr>
		</param>
	</else>
	</if>

	<param id='boolparam' type='bool'>
		<expr>if1.p1 or boolp1 or boolp2 or boolp3</expr>
	</param>

</signalml>

=== BrainTech/jsignalml/specs/XML.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE signalml SYSTEM "SignalML_2_0.dtd">
<signalml>
	<header>
		<text_info>SignalML definition for XML header file and binary data
			file</text_info>
	</header>
	<file id='main' type='xml'>
		<param id='export_file_name' type='str'>
			<xpath xpath-evaluation-type='node-content-text'>'/rs:rawSignal/rs:exportFileName'</xpath>
		</param>

		<param id='data_filename' type='str'>
			<xpath xpath-evaluation-type='node-content-text'>'/rs:rawSignal/rs:sourceFileName'</xpath>
		</param>

		<param id='source_file_format' type='str'>
			<xpath xpath-evaluation-type='node-name-local'>'/rs:rawSignal/rs:sourceFileFormat'</xpath>
		</param>

		<param id='sampling_frequency' type='float' units='Hz'>
			<xpath xpath-evaluation-type='node-content-float'>'/rs:rawSignal/rs:samplingFrequency'</xpath>
		</param>

		<param id='total_channels' type='int'>
			<xpath xpath-evaluation-type='node-content-int'>'/rs:rawSignal/rs:channelCount'</xpath>
		</param>

		<param id='number_of_samples' type='int'>
			<xpath xpath-evaluation-type='node-content-int'>'/rs:rawSignal/rs:sampleCount'</xpath>
		</param>

		<param id='calibration' type='float'>
			<xpath xpath-evaluation-type='node-content-float'>'/rs:rawSignal/rs:calibration'</xpath>
		</param>

		<param id='sample_format' type='str'>
			<xpath xpath-evaluation-type='node-content-text'>'/rs:rawSignal/rs:sampleType'</xpath>
		</param>

		<param id='byte_order' type='str'>
			<xpath xpath-evaluation-type='node-content-text'>'/rs:rawSignal/rs:byteOrder'</xpath>
		</param>

		<param id='page_size' type='float'>
			<xpath xpath-evaluation-type='node-content-float'>'/rs:rawSignal/rs:pageSize'</xpath>
		</param>

		<param id='blocks_per_page' type='int'>
			<xpath xpath-evaluation-type='node-content-int'>'/rs:rawSignal/rs:blocksPerPage'</xpath>
		</param>

		<param id='first_sample_timestamp' type='str'>
			<xpath xpath-evaluation-type='node-content-text'>'/rs:rawSignal/rs:firstSampleTimestamp'</xpath>
		</param>

		<param id='sample_unit' type='float'>
			<expr>1</expr>
		</param>

		<file id='data_file' type='binary' filename='data_filename'>
		</file>

		<if id='order' test='byte_order == "LITTLE_ENDIAN"'>
			<param id='order_value' type='str'>
				<expr>"&lt;"</expr>
			</param>
			<else-if test='byte_order == "BIG_ENDIAN"'>
				<param id='order_value' type='str'>
					<expr>"&gt;"</expr>
				</param>
			</else-if>
		</if>

		<if id='size' test='sample_format == "SHORT"'>
			<param id='sample_size_value' type='int'>
				<expr>2</expr>
			</param>
			<else-if test='sample_format == "LONG"'>
				<param id='sample_size_value' type='int'>
					<expr>4</expr>
				</param>
				<else-if test='sample_format == "FLOAT"'>
					<param id='sample_size_value' type='int'>
						<expr>4</expr>
					</param>
					<else-if test='sample_format == "DOUBLE"'>
						<param id='sample_size_value' type='int'>
							<expr>8</expr>
						</param>
					</else-if>
				</else-if>
			</else-if>
		</if>

		<if id='format' test='sample_format == "SHORT"'>
			<param id='sample_format_value' type='str'>
				<expr>order.order_value + "i2"</expr>
			</param>
			<else-if test='sample_format == "LONG"'>
				<param id='sample_format_value' type='str'>
					<expr>order.order_value + "i4"</expr>
				</param>

				<else-if test='sample_format == "FLOAT"'>
					<param id='sample_format_value' type='str'>
						<expr>order.order_value + "f4"</expr>
					</param>
					<else-if test='sample_format == "DOUBLE"'>
						<param id='sample_format_value' type='str'>
							<expr>order.order_value + "f8"</expr>
						</param>
					</else-if>
				</else-if>
			</else-if>

		</if>

		<param id='sample_size' type='int'>
			<expr>size.sample_size_value</expr>
		</param>

		<param id='sample_format_type' type='str'>
			<expr>str(format.sample_format_value)</expr>
		</param>

		<channelset id='data_test'>

			<for-each id='channels' var='index' sequence='range(total_channels)'
				type='int'>

				<param id='channel_name_expr' type='str'>
					<expr>"(/rs:rawSignal/rs:channelLabels/rs:label)[" + str(index+1) +
						"]"</expr>
				</param>

				<param id='channel_name' type='str'>
					<xpath xpath-evaluation-type='node-content-text'>channel_name_expr</xpath>
				</param>

				<param id='calibration_gain_expr' type='str'>
					<expr>"(/rs:rawSignal/rs:calibrationGain/rs:calibrationParam)[" +
						str(index+1) + "]"</expr>
				</param>

				<param id='calibration_gain' type='str'>
					<xpath xpath-evaluation-type='node-content-text'>calibration_gain_expr</xpath>
				</param>

				<param id='calibration_offset_expr' type='str'>
					<expr>"(/rs:rawSignal/rs:calibrationOffset/rs:calibrationParam)[" +
						str(index+1) + "]"</expr>
				</param>

				<param id='calibration_offset' type='str'>
					<xpath xpath-evaluation-type='node-content-text'>calibration_offset_expr</xpath>
				</param>

				<channel mapping='mapping' format='sample_format_type'
					length='number_of_samples' data='data_file' fast='1' />

				<param id='mapping' type='int'>
					<arg type='int' name='sample' />
					<expr>(sample * total_channels + index) * sample_size</expr>
				</param>

			</for-each>
		</channelset>

	</file>
</signalml>

=== BrainTech/jsignalml/specs/EASYS.xml
<?xml version="1.0"?>
<!DOCTYPE signalml SYSTEM "SignalML_2_0.dtd">
<signalml>
  <header>
      <text_info>PE-EASYS</text_info>
  </header>

  <file type='binary' id='main'><!-- extension='*.d' -->
     <param id='datatype_width'>
        <expr>4</expr>
     </param>
     <param id='mapping' type='int'>
        <arg type='int' name='sample_number' />
        <arg type='int' name='channel_number' />
        <expr>(number_of_channels * sample_number + channel_number) *
                  datatype_width + 16 * data_offset
        </expr>
     </param>

     <param id='signature'>
        <format>'|S15'</format>
        <offset>0</offset>
     </param>
     <param id='magic'>
	 <expr>signature[:3]</expr>
     </param>
     <assert id='magic_ok'>
         <expr>magic == "EAS"</expr>
     </assert>

     <param id='file_type'>
	 <!-- D or R -->
         <format>'|S1'</format>
         <offset>15</offset>
     </param>
     <assert id='file_type_ok'>
         <expr>file_type == "D"</expr>
     </assert>

     <param id='number_of_channels'>
         <format>'|u1'</format>
         <offset>16</offset>
     </param>

     <param id='number_of_auxiliary_channels'>
         <format>'|u1'</format>
         <offset>17</offset>
     </param>

     <param id='sampling_frequency' type='float' units='Hz'>
         <format>'&lt;u2'</format>
         <offset>18</offset>
     </param>

     <param id='number_of_samples'>
         <format>'&lt;i4'</format>
         <offset>20</offset>
     </param>

     <param id='data_validation_field'>
	 <!-- flags ... -->
         <format>'|i1'</format>
         <offset>24</offset>
     </param>

     <param id='data_cell_size'>
	 <expr>2**(data_validation_field &amp; 3 - 1)</expr>
     </param>
     <assert id='data_cell_size_ok'>
	 <expr>(file_type == 'D' and data_cell_size == 2)
	     or (file_type == 'R' and data_cell_size == 4)
	 </expr>
     </assert>

     <!-- more 'flags' should follow -->

     <param id='calibration_gain' type='float' units='Î¼V'>
         <expr>1/_calibration_unit</expr>
     </param>
     <param id='_calibration_unit'>
         <format>'|u1'</format>
         <offset>25</offset>
     </param>

     <param id='calibration_offset'>
         <format>'&lt;i2'</format>
         <offset>26</offset>
     </param>

     <param id='data_org'>
	 <!-- data offset -->
         <format>'&lt;u2'</format>
         <offset>28</offset>
     </param>
     <param id='data_offset'>
	 <expr>data_org * 16</expr>
     </param>

     <param id='xhdr_org' type='int'>
	 <!-- data offset -->
         <format>'&lt;u2'</format>
         <offset>30</offset>
     </param>
     <param id='extended_header_offset'>
	 <expr>xhdr_org * 16</expr>
     </param>

     <for-each id='extended_header' var='index' sequence='[0,1,2,3,4,5]'>
         <param id='offset' type='int'>
	   <expr>index == 0 ? extended_header_offset : extended_header[index-1].offset +
	                                 extended_header[index-1].record_size + 4</expr>
	 </param>
         <param id='record_mnemonic' type='str'>
           <format>'|S2'</format>
	   <offset>offset</offset>
	 </param>
         <param id='record_size' type='int'>
           <format>'&lt;i2'</format>
	   <offset>offset + 2</offset>
	 </param>
     </for-each>

     <channelset id='data'>
       <for-each id='channels' var='index' sequence='range(number_of_channels)'>
	 <channel mapping='mapping' format='"&lt;i2"' />

	 <param id='mapping' type='int'>
	   <arg type='int' name='sample' />
	   <expr>data_offset + (sample * number_of_samples + index) * data_cell_size</expr>
	 </param>
       </for-each>
     </channelset>

     <param id='type_map_name'>
         <expr>
	   {'AU': 'Authentication_key',
	    'FS': 'Frequency_of_Sampling',
           }
	 </expr>
     </param>
  </file>
</signalml>

=== BrainTech/jsignalml/specs/TextFile.xml
<?xml version="1.0"?>
<!DOCTYPE signalml SYSTEM "SignalML_2_0.dtd">
<signalml>

	<header>
		<text_info>test file for text type</text_info>
		<url>sometestfile</url>
	</header>


	<file id='main' type='text'>
		<!---->
		<param id='number_of_channels' type='int'>
			<format>'|u1'</format>
			<line>-1</line>
			<pattern>"MSI.MegChanCount: ([0-9]*)"</pattern>
			<group>1</group>
		</param>

		<param id='sampling_frequency' type='float' units='Hz'>
			<format>'&lt;f4'</format>
			<line>-1</line>
			<pattern>"MSI.SampleFrequency: ([0-9]+.[0-9]*)"</pattern>
			<group>1</group>
		</param>

		<param id='number_of_samples' type='int'>
			<expr>slices_per_epoch * total_epochs </expr>
		</param>

		<param id='meg_chan_index' type='str'>
			<format>'|S2'</format>
			<line>-1</line>
			<pattern>"MSI.MegChanIndex: ([0-9,]+)$"</pattern>
			<group>1</group>
		</param>

		<param id='total_epochs' type='int'>
			<format>'|u1'</format>
			<line>-1</line>
			<pattern>"MSI.TotalEpochs: ([0-9]*)"</pattern>
			<group>1</group>
		</param>

		<param id='slices_per_epoch' type='int'>
			<format>'|u1'</format>
			<line>-1</line>
			<pattern>"MSI.SlicesPerEpoch: ([0-9]*)"</pattern>
			<group>1</group>
		</param>

		<param id='total_channels' type='int'>
			<format>'|u1'</format>
			<line>-1</line>
			<pattern>"MSI.TotalChannels: ([0-9]*)"</pattern>
			<group>1</group>
		</param>

		<param id='get_data_filename' type='str'>
			<format>'|S2'</format>
			<line>-1</line>
			<pattern>"MSI.FileDescriptor: (.+;){4}([a-zA-Z0-9,._-]+)"</pattern>
			<group>2</group>
		</param>

		<channelset id='data_test' filename='a.txt'>

			<for-each id='channels' var='index' sequence='range(number_of_channels)'>
				<channel mapping='mapping' format='"&gt;f4"' 
							length='number_of_samples' data='data_file' fast='1' />
				
				<file id='data_file' type='binary' filename='get_data_filename'>
				</file>
				
				<param id='channel_name' type='str'>
					<format>'|S1'</format>
					<line>-1</line>
					<pattern>single_channel_name_pattern</pattern>
					<group>2</group>
				</param>

				<param id='single_channel_name_pattern' type='str'>
					<expr>"MSI.MegChanNames: ([a-zA-Z0-9]+,){" + str(index) + "}([A-Za-z0-9]+)"</expr>
				</param>

				<param id='channel_index' type='int'>
					<format>'|u1'</format>
					<line>-1</line>
					<pattern>single_channel_index_pattern</pattern>
					<group>2</group>
				</param>

				<param id='single_channel_index_pattern' type='str'>
					<expr>"MSI.MegChanIndex: ([0-9]+,){" + str(index) + "}([0-9]+)"</expr>
				</param>

				<param id='mapping' type='int'>
					<arg type='int' name='sample' />
					<expr>(sample*total_channels + channel_index -1) * 4</expr>
				</param>

				<param id='calibration_gain' type='float' units='Î¼V'>
					<expr>'1.0e15f'</expr>
				</param>

 			</for-each>
		</channelset>


	</file>

</signalml>

=== BrainTech/jsignalml/specs/accesstest.xml
<?xml version="1.0"?>
<!DOCTYPE signalml SYSTEM "SignalML_2_0.dtd">
<signalml>

  <header>
    <text_info>testfile for access()</text_info>
    <url>http://wheredoyouwantogotoday.to</url>
  </header>

  <param id='p1' type='int'>
    <expr>333</expr>
  </param>

  <param id='p2' type='int'>
    <expr>p1 * 3</expr>
  </param>

  <param id='func' type='str'>
    <arg name='count' />
    <expr>count * 'a'</expr>
  </param>

  <param id='p3' type='str'>
    <expr>func(3)</expr>
  </param>

  <file id='data' type='binary'>
    <param id='r1' type='int'>
      <format>'&lt;i2'</format>
      <offset>0</offset>
    </param>
  </file>
</signalml>

=== BrainTech/jsignalml/specs/test/iftest.xml
<?xml version="1.0"?>
<!DOCTYPE signalml SYSTEM "SignalML_2_0.dtd">
<signalml>

  <header>
    <format_id><info>testfile for ifs</info></format_id>
    <url>http://wheredoyouwantogotoday.to</url>
  </header>

  <if id='if1' test='1'>
    <param id='p1' type='int'>
      <expr>333</expr>
    </param>
    <else>
      <param id='p1' type='str'>
	<expr>333</expr>
      </param>
    </else>
  </if>

  <param id='p2'>
    <expr>if1.p1 * 2</expr>
  </param>

  <param id='requires_builtin_strip'>
    <expr>strip('aaa ')</expr>
  </param>

  <param id='wrap_builtin_strip'>
    <arg name='s' type='str' />
    <expr>strip(s)</expr>
  </param>

  <param id='call_wrap_builtin_strip'>
    <expr>wrap_builtin_strip(' bbb ')</expr>
  </param>

  <param id='test_range_1'>
    <expr>range(30)</expr>
  </param>

  <param id='test_range_2'>
    <expr>range(3, 30)</expr>
  </param>

  <param id='test_range_3'>
    <expr>range(2, 30, 5)</expr>
  </param>
</signalml>
