=== BrainTech/jsignalml/src/main/resources/jsignaml/xml/SignalML_2_0.dtd
<!ENTITY % standard_elements "param | assert | file | for-each | if | channelset | channel">
<!ELEMENT signalml (header, (%standard_elements;)*)>

<!ELEMENT header (format_id | codec_id | url)*>
<!ELEMENT format_id (name | provider | version | info)*>
<!ELEMENT codec_id (provider | version | info)*>

<!ELEMENT url (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT provider (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT info (#PCDATA)>

<!ELEMENT file (%standard_elements;)*>
<!ELEMENT param (arg*,
          (expr
          | (offset, format) | (format, offset)
          | (pattern, group, line?) | (pattern, line?, group?) | (line, pattern, group?)
	  | (xpath) )
)>
<!ELEMENT assert (expr)>
<!ELEMENT arg EMPTY>
<!ELEMENT if (%standard_elements; | else-if | else)*>
<!ELEMENT else-if (%standard_elements; | else-if | else)*>
<!ELEMENT else (%standard_elements;)*>
<!ELEMENT for-each (%standard_elements;)*>
<!ELEMENT channelset (%standard_elements;)*>
<!ELEMENT channel (%standard_elements;)*>

<!ENTITY % file_types "binary|text|xml">

<!ELEMENT expr (#PCDATA)>
<!ELEMENT offset (#PCDATA)>
<!ELEMENT format (#PCDATA)>
<!ELEMENT pattern (#PCDATA)>
<!ELEMENT line (#PCDATA)>
<!ELEMENT group (#PCDATA)>
<!ELEMENT xpath (#PCDATA)>

<!ATTLIST file
	  type   (%file_types;) #REQUIRED
          name   CDATA #IMPLIED
          id     CDATA #IMPLIED
          filename CDATA #IMPLIED
>
<!ATTLIST param
	  id     CDATA #REQUIRED
	  type   CDATA #IMPLIED
	  units  CDATA #IMPLIED
>
<!ATTLIST assert
	  id     CDATA #IMPLIED
>
<!ATTLIST arg
	  type   CDATA #IMPLIED
	  name   CDATA #REQUIRED
>
<!ATTLIST for-each
	  id     CDATA #IMPLIED
	  var    CDATA #IMPLIED
	  sequence CDATA #REQUIRED
	  type   CDATA #IMPLIED
>
<!ATTLIST if
	  id     CDATA #IMPLIED
	  test   CDATA #REQUIRED
>
<!ATTLIST else-if
	  test   CDATA #REQUIRED
>
<!ATTLIST channelset
	  id     CDATA #IMPLIED
>
<!ATTLIST channel
	  id     CDATA #IMPLIED
	  mapping CDATA #IMPLIED
	  format CDATA #IMPLIED
	  length CDATA #IMPLIED
	  data   CDATA #IMPLIED
	  fast   CDATA #IMPLIED
>
<!ATTLIST line
	  type   CDATA #IMPLIED
>
<!ATTLIST xpath
	  id     CDATA #IMPLIED
	  xpath-evaluation-type CDATA #IMPLIED
	  xpath-attribute-name CDATA #IMPLIED
	  type   CDATA #IMPLIED
>

=== BrainTech/jsignalml/specs/elseiftest.xml
<?xml version="1.0"?>
<!DOCTYPE signalml SYSTEM "SignalML_2_0.dtd">
<signalml>

	<header>
		<format_id>
		  <info>
		    testfile for ifs
		  </info>
		</format_id>
	</header>

	<param id='p1' type='int'>
		<expr>1</expr>
	</param>
	<if id='if1' test='1'>
		<param id='p1' type='int'>
			<expr>1</expr>
		</param>
		<else-if test='0'>
			<param id='p1' type='int'>
				<expr>2</expr>
			</param>
			<else-if test='0'>
				<param id='p1' type='int'>
					<expr>3</expr>
				</param>
				<else>
					<param id='p1' type='int'>
						<expr>4</expr>
					</param>
				</else>
			</else-if>
		</else-if>

		<if id='if11' test='1'>
			<param id='p1' type='int'>
				<expr>1</expr>
			</param>
			<else-if test='0'>
				<param id='p1' type='int'>
					<expr>2</expr>
				</param>
				<else-if test='0'>
					<param id='p1' type='int'>
						<expr>3</expr>
					</param>
					<else>
						<param id='p1' type='int'>
							<expr>4</expr>
						</param>
					</else>
				</else-if>
			</else-if>

			<if id='if111' test='0'>
				<param id='p1' type='int'>
					<expr>1</expr>
				</param>
				<else-if test='1'>
					<param id='p1' type='int'>
						<expr>2</expr>
					</param>
					<else-if test='0'>
						<param id='p1' type='int'>
							<expr>3</expr>
						</param>
						<else>
							<param id='p1' type='int'>
								<expr>4</expr>
							</param>
						</else>
					</else-if>

					<if id='if1111' test='0'>
						<param id='p1' type='int'>
							<expr>1</expr>
						</param>
						<else-if test='0'>
							<param id='p1' type='int'>
								<expr>2</expr>
							</param>
							<else-if test='1'>
								<param id='p1' type='int'>
									<expr>3</expr>
								</param>
								<else>
									<param id='p1' type='int'>
										<expr>4</expr>
									</param>
								</else>

								<if id='if11111' test='0'>
									<param id='p1' type='int'>
										<expr>1</expr>
									</param>
									<else-if test='0'>
										<param id='p1' type='int'>
											<expr>2</expr>
										</param>
										<else-if test='0'>
											<param id='p1' type='int'>
												<expr>3</expr>
											</param>
											<else>
												<param id='p1' type='int'>
													<expr>4</expr>
												</param>
											</else>
										</else-if>
									</else-if>
								</if>

							</else-if>
						</else-if>
					</if>

				</else-if>
			</if>

		</if>

	</if>

	<param id='p2'>
		<expr>p1 * 100000 + if1.p1 * 10000 + if1.if11.p1 * 1000 + if1.if11.if111.p1 * 100 + if1.if11.if111.if1111.p1 * 10 + if1.if11.if111.if1111.if11111.p1 * 1</expr>
	</param>

</signalml>

=== BrainTech/jsignalml/specs/M4D.xml
<?xml version="1.0"?>
<!DOCTYPE signalml SYSTEM "SignalML_2_0.dtd">
<signalml>

	<header>
		<text_info>SignalML definition for 4D format</text_info>
	</header>


	<file id='main' type='text'>
		<!---->
		<param id='number_of_channels' type='int'>
			<pattern>"MSI.MegChanCount: ([0-9]*)"</pattern>
			<group>1</group>
		</param>

		<param id='sampling_frequency' type='float' units='Hz'>
			<pattern>"MSI.SampleFrequency: ([0-9]+.[0-9]*)"</pattern>
			<group>1</group>
		</param>

		<param id='number_of_samples' type='int'>
			<expr>slices_per_epoch * total_epochs </expr>
		</param>

		<param id='meg_chan_index' type='str'>
			<pattern>"MSI.MegChanIndex: ([0-9,]+)$"</pattern>
			<group>1</group>
		</param>

		<param id='total_epochs' type='int'>
			<pattern>"MSI.TotalEpochs: ([0-9]*)"</pattern>
			<group>1</group>
		</param>

		<param id='slices_per_epoch' type='int'>
			<pattern>"MSI.SlicesPerEpoch: ([0-9]*)"</pattern>
			<group>1</group>
		</param>

		<param id='total_channels' type='int'>
			<pattern>"MSI.TotalChannels: ([0-9]*)"</pattern>
			<group>1</group>
		</param>

		<param id='data_filename' type='str'>
			<pattern>"MSI.FileDescriptor: (.+;){4}([a-zA-Z0-9,._-]+)"</pattern>
			<group>2</group>
		</param>

		<param id='sample_unit' type='float'>
			<expr>1</expr>
		</param>

		<param id='unit' type='str'>
			<expr>'Î¼V'</expr>
		</param>

		<param id='calibration_gain' type='float'>
			<expr>1.0e15</expr>
		</param>

		<file id='data_file' type='binary' filename='data_filename'>
		</file>

		<param id='msi_format' type='str'>
			<pattern>"MSI.Format: ([a-zA-Z]+)"</pattern>
			<group>1</group>
		</param>

		<if id='size' test='msi_format == "SHORT"'>
			<param id='sample_size_1' type='int'>
				<expr>2</expr>
			</param>

			<else-if test='msi_format == "LONG"'>
				<param id='sample_size_1' type='int'>
					<expr>4</expr>
				</param>

				<else>  <!-- test='msi_format == "FLOAT"'> -->
					<param id='sample_size_1' type='int'>
						<expr>4</expr>
					</param>
				</else>
			</else-if>

		</if>

		<if id='format' test='msi_format == "SHORT"'>
			<param id='sample_format_1' type='str'>
				<expr>"&gt;i2"</expr>
			</param>

			<else-if test='msi_format == "LONG"'>
				<param id='sample_format_1' type='str'>
					<expr>"&gt;i4"</expr>
				</param>

				<else>  <!-- test='msi_format == "FLOAT"'> -->
					<param id='sample_format_1' type='str'>
						<expr>"&gt;f4"</expr>
					</param>
				</else>
			</else-if>

		</if>

<!--   TODO: apply if-else for DOUBLE format
		<else-if id='format' test='msi_format == "LONG"'>
			<param id='sample_size_1' type='int'>
				<expr>4</expr>
			</param>
			<param id='sample_format_1' type='str'>
				<expr>"&gt;i4"</expr>
			</param>
		</else-if>
 -->

		<param id='sample_size' type='int'>
			<expr>size.sample_size_1</expr>
		</param>

		<param id='sample_format' type='str'>
			<expr>str(format.sample_format_1)</expr>
		</param>

		<channelset id='data_test'>

			<for-each id='channels' var='index' sequence='range(number_of_channels)'
				type='int'>
				<channel mapping='mapping' format='sample_format' length='number_of_samples'
					data='data_file' />


				<param id='channel_name' type='str'>
					<pattern>single_channel_name_pattern</pattern>
					<group>2</group>
				</param>

				<param id='channel_type_name' type='str'>
					<expr>'MEG'</expr>
				</param>

				<param id='single_channel_name_pattern' type='str'>
					<expr>"MSI.MegChanNames: ([a-zA-Z0-9]+,){" + str(index) +
						"}([A-Za-z0-9]+)"</expr>
				</param>

				<param id='channel_index' type='int'>
					<pattern>single_channel_index_pattern</pattern>
					<group>2</group>
				</param>

				<param id='single_channel_index_pattern' type='str'>
					<expr>"MSI.MegChanIndex: ([0-9]+,){" + str(index) + "}([0-9]+)"</expr>
				</param>

				<param id='mapping' type='int'>
					<arg type='int' name='sample' />
					<expr>(sample*total_channels + channel_index -1) * sample_size</expr>
				</param>

			</for-each>
		</channelset>


	</file>

</signalml>

=== BrainTech/jsignalml/specs/New4D.xml
<?xml version="1.0"?>
<!DOCTYPE signalml SYSTEM "SignalML_2_0.dtd">
<signalml>
	<header>
		<format_id>
			<name>New 4D format</name>
			<provider>-</provider>
			<version>1.0.0</version>
			<info>New 4D format</info>
		</format_id>
		<codec_id>
			<provider>Ericpol</provider>
			<version>1.0.0</version>
		</codec_id>
	</header>
	<file id='main' type='text'>
		<param id='number_of_blocks' type='int'>
			<expr>8</expr>
		</param>
		<param id='data_filename' type='str'>
			<expr>fetch(get_filename(main), "([a-zA-Z0-9_,.;]+.)hdr", 1) + "data"</expr>
		</param>
		<param id='file_type' type='str'>
			<pattern>"[ ]*File[ _]*[Tt]{1}ype[ ]*:[ ]*\'([A-Za-z]*)\'"</pattern>
			<group>1</group>
		</param>
		<param id='sampling_frequency' type='float' units='Hz'>
			<pattern>"[ ]*Sample[ _]*[Ff]{1}requency[ ]*:[ ]*([0-9]+[.0-9e+]*)"</pattern>
			<group>1</group>
		</param>
		<param id='data_format' type='str'>
			<pattern>"[ ]*Data[ _]*[Ff]{1}ormat[ ]*:[ ]*([A-Za-z,]*)"</pattern>
			<group>1</group>
		</param>
		<param id='total_number_of_channels' type='int'>
			<pattern>"[ ]*([0-9]*)[ ]+channels[ ]*$"</pattern>
			<group>1</group>
		</param>
		<param id='MEG_channel_group' type='int'>
			<pattern>"[ ]*([0-9]*)[ ]+MEG[ ]*channels[,]{1}[ ]*group[ ]*([0-9]*)"</pattern>
			<group>2</group>
		</param>
		<param id='line_pattern_for_channel_sensitivities' type='str'>
			<expr>"^[ ]*([A-Za-z0-9]+)[ ]+([0-9]+)[ ]+([0-9e+-.]+)[ ]+([a-zA-Z]+)[ ]*$"</expr>
		</param>
		<param id='line_number_with_channel_sensitivities' type='int'>
			<expr>get_line_for_pattern(main, line_pattern_for_channel_sensitivities, 0)</expr>
		</param>
		<param id='longest_epoch_nr' type='int'>
			<pattern>"[ ]*Epoch[ _]*([0-9]*)[ ]*:[ ]*([0-9]*)[ ]+slices[,]{1}[ ]*([0-9]+[.]{1}[0-9]*)"</pattern>
			<group>1</group>
		</param>
		<param id='number_of_samples' type='int'>
			<pattern>"[ ]*Epoch[ _]*([0-9]*)[ ]*:[ ]*([0-9]*)[ ]+slices[,]{1}[ ]*([0-9]+[.]{1}[0-9]*)"</pattern>
			<group>2</group>
		</param>
		<param id='msi_format' type='str'>
			<expr>data_format</expr>
		</param>
		<if id='size' test='msi_format == "bigendian,short"'>
			<param id='sample_size_1' type='int'>
				<expr>2</expr>
			</param>
			<else-if test='msi_format == "bigendian,float"'>
				<param id='sample_size_1' type='int'>
					<expr>4</expr>
				</param>
				<else-if test='msi_format == "ASCII"'>
					<param id='sample_size_1' type='int'>
						<expr>1</expr>
					</param>
					<else>
						<param id='sample_size_1' type='int'>
							<expr>0</expr>
						</param>
					</else>
				</else-if>
			</else-if>
		</if>
		<if id='format' test='msi_format == "bigendian,short"'>
			<param id='sample_format_1' type='str'>
				<expr>"&gt;i2"</expr>
			</param>
			<else-if test='msi_format == "bigendian,float"'>
				<param id='sample_format_1' type='str'>
					<expr>"&gt;f4"</expr>
				</param>
				<else-if test='msi_format == "ASCII"'>
					<param id='sample_format_1' type='str'>
						<expr>"|S0"</expr>
					</param>
					<else>
						<param id='sample_format_1' type='str'>
							<expr>"|S0"</expr>
						</param>
					</else>
				</else-if>
			</else-if>
		</if>
		<param id='sample_size' type='int'>
			<expr>size.sample_size_1</expr>
		</param>
		<param id='sample_format' type='str'>
			<expr>str(format.sample_format_1)</expr>
		</param>

		<file id='data_file' type='binary' filename='data_filename' />

		<channelset id='data_test'>
			<for-each id='channels' var='line_nr' sequence='range(total_number_of_channels)' type='int'>
				<param id='line_nr_channel_sensitivities' type='int'>
					<expr>line_number_with_channel_sensitivities + line_nr</expr>
				</param>
				<param id='channel_group' type='int'>
					<line type='int'>line_nr_channel_sensitivities</line>
					<pattern>line_pattern_for_channel_sensitivities</pattern>
					<group>2</group>
				</param>
				<if test='channel_group == MEG_channel_group'>
					<param id='channel_name' type='str'>
						<line type='int'>line_nr_channel_sensitivities</line>
						<pattern>line_pattern_for_channel_sensitivities</pattern>
						<group>1</group>
					</param>
					<param id='channel_type' type='str'>
						<expr>'MEG'</expr>
					</param>
					<param id='channel_sensitivity' type='float'>
						<line type='int'>line_nr_channel_sensitivities</line>
						<pattern>line_pattern_for_channel_sensitivities</pattern>
						<group>3</group>
					</param>
					<param id='channel_sensitivity_unit' type='str'>
						<line type='int'>line_nr_channel_sensitivities</line>
						<pattern>line_pattern_for_channel_sensitivities</pattern>
						<group>4</group>
					</param>
					<param id='unit' type='str'>
						<expr>str(channel_sensitivity_unit)</expr>
					</param>
					<param id='calibration_gain' type='float'>
						<expr>channel_sensitivity</expr>
					</param>
					<channel id='channel' mapping='mapping' format='sample_format'
								length='number_of_samples' data='data_file'>
						<param id='mapping' type='int'>
							<arg type='int' name='sample' />
							<expr>(sample * total_number_of_channels + line_nr) * sample_size</expr>
						</param>
					</channel>
				</if>
			</for-each>
		</channelset>
	</file>
</signalml>

=== BrainTech/jsignalml/specs/ALT.xml
<?xml version="1.0"?>
<!DOCTYPE signalml SYSTEM "SignalML_2_0.dtd">
<signalml>
	<header>
		<format_id>
			<name>ALT format</name>
			<provider>-</provider>
			<version>1.0.0</version>
		</format_id>
		<codec_id>
			<provider>UW</provider>
			<version>1.0.0</version>
		</codec_id>
	</header>
	<file id='main' type='text'>

		<!-- global header items -->
		<param id='number_of_channels' type='int'>
			<pattern>"number_of_channels: ([0-9]+.[0-9]*)"</pattern>
			<group>1</group>
		</param>
		<param id='sample_size' type='int'>
			<expr>4</expr>
		</param>
		<param id='sample_format' type='str'>
			<expr>str("&gt;i4")</expr>
		</param>

		<!-- set of channels -->
		<channelset id='data'>
			<for-each id='channels' var='index' sequence='range(number_of_channels)' type='int'>

				<!-- local header patterns -->
				<param id='channel_name_pattern' type='str'>
					<expr>"channel_names: ([a-zA-Z0-9]+,){" + str(index) + "}([A-Za-z0-9]+)"</expr>
				</param>
				<param id='channel_type_name_pattern' type='str'>
					<expr>"channel_types: ([a-zA-Z0-9]+,){" + str(index) + "}([A-Za-z0-9]+)"</expr>
				</param>
				<param id='channel_filename_pattern' type='str'>
					<expr>"channel_filenames: ([a-zA-Z0-9._-]+,){" + str(index) + "}([a-zA-Z0-9._-]+)"</expr>
				</param>
				<param id='channel_sampling_frequency_pattern' type='str'>
					<expr>"channel_sampling_frequencies: ([0-9.eE]+,){" + str(index) + "}([0-9.eE]+)"</expr>
				</param>
				<param id='channel_nr_of_samples_pattern' type='str'>
					<expr>"channel_nrs_of_samples: ([0-9]+,){" + str(index) + "}([0-9]+)"</expr>
				</param>
				<param id='calibration_gain_pattern' type='str'>
					<expr>"channel_calibration_gains: ([0-9.eE]+,){" + str(index) + "}([0-9.eE]+)"</expr>
				</param>
				<param id='calibration_offset_pattern' type='str'>
					<expr>"channel_calibration_offsets: ([0-9.eE]+,){" + str(index) + "}([0-9.eE]+)"</expr>
				</param>

				<!-- local header items -->
				<param id='channel_name' type='str'>
					<pattern>channel_name_pattern</pattern>
					<group>2</group>
				</param>
				<param id='channel_type' type='str'>
					<pattern>channel_type_name_pattern</pattern>
					<group>2</group>
				</param>
				<param id='channel_filename' type='str'>
					<pattern>channel_filename_pattern</pattern>
					<group>2</group>
				</param>
				<param id='sampling_frequency' type='float' units='Hz'>
					<pattern>channel_sampling_frequency_pattern</pattern>
					<group>2</group>
				</param>
				<param id='number_of_samples' type='int'>
					<pattern>channel_nr_of_samples_pattern</pattern>
					<group>2</group>
				</param>
				<param id='unit' type='str'>
					<expr>'Î¼V'</expr>
				</param>
				<param id='calibration_gain' type='float'>
					<pattern>calibration_gain_pattern</pattern>
					<group>2</group>
				</param>
				<param id='calibration_offset' type='float'>
					<pattern>calibration_offset_pattern</pattern>
					<group>2</group>
				</param>

				<!-- body items -->
				<file id='channel_file' type='binary' filename='channel_filename'>
				</file>
				<channel mapping='mapping' format='sample_format' length='number_of_samples' data='channel_file'>
					<param id='mapping' type='int'>
						<arg type='int' name='sample_nr' />
						<expr>sample_nr * sample_size</expr>
					</param>
				</channel>

 			</for-each>
		</channelset>

	</file>
</signalml>

=== BrainTech/jsignalml/specs/test/uinttypetest.xml
<?xml version="1.0"?>
<!DOCTYPE signalml SYSTEM "SignalML_2_0.dtd">
<signalml>
  <header>
    <format_id>
      <name>Unsigned Integer Type Test</name>
      <provider>-</provider>
      <version>0.0.0</version>
    </format_id>
  </header>
  <file type='binary' id='main'>
    <param id='def_len'>
      <format>'&lt;u2'</format>
      <offset>4</offset>
    </param>
  </file>
</signalml>
